/**
 * Data access layer — reads from local JSON or Supabase
 * For now, we read from the data/processed directory (generated by the pipeline)
 */

import { readFileSync, existsSync } from 'fs';
import { join } from 'path';

const DATA_DIR = join(process.cwd(), 'data/processed');

function loadJSON<T>(filename: string): T[] {
  const path = join(DATA_DIR, filename);
  if (!existsSync(path)) return [];
  return JSON.parse(readFileSync(path, 'utf-8'));
}

export interface WaterScore {
  system_id: string;
  system_name: string;
  state: string;
  city: string;
  zip_code: string;
  population_served: number;
  overall_score: number;
  grade: string;
  violation_score: number;
  contaminant_score: number;
  source_score: number;
  infrastructure_score: number;
  size_score: number;
  total_violations: number;
  unresolved_violations: number;
  total_contaminant_samples: number;
  mcl_exceedances: number;
  top_concerns: string[];
  updated_at: string;
}

export interface Violation {
  id: string;
  system_id: string;
  contaminant_code: string;
  violation_type: string;
  is_health_based: boolean;
  is_major: boolean;
  is_resolved: boolean;
  begin_date: string;
  end_date: string | null;
}

export interface ContaminantSample {
  id: string;
  system_id: string;
  contaminant_code: string;
  contaminant_name: string;
  measured_value: number;
  unit: string;
  mcl: number | null;
  exceeds_mcl: boolean | null;
  category: string;
  health_effects: string;
}

// ---- Data access functions ----

let scoresCache: WaterScore[] | null = null;

function getScores(): WaterScore[] {
  if (!scoresCache) scoresCache = loadJSON<WaterScore>('water_scores.json');
  return scoresCache;
}

export function getScoreBySystemId(systemId: string): WaterScore | undefined {
  return getScores().find(s => s.system_id === systemId);
}

export function getScoresByState(state: string): WaterScore[] {
  return getScores().filter(s => s.state === state);
}

export function getScoresByCity(state: string, city: string): WaterScore[] {
  return getScores().filter(s => 
    s.state.toLowerCase() === state.toLowerCase() && 
    s.city.toLowerCase() === city.toLowerCase()
  );
}

export function getScoresByZip(zip: string): WaterScore[] {
  return getScores().filter(s => s.zip_code === zip);
}

export function searchSystems(query: string, limit = 20): WaterScore[] {
  const q = query.toLowerCase().trim();
  return getScores()
    .filter(s => 
      s.system_name.toLowerCase().includes(q) ||
      s.city.toLowerCase().includes(q) ||
      s.zip_code?.includes(q) ||
      s.state.toLowerCase() === q
    )
    .slice(0, limit);
}

export function getWorstSystems(limit = 20): WaterScore[] {
  return [...getScores()].sort((a, b) => a.overall_score - b.overall_score).slice(0, limit);
}

export function getBestSystems(limit = 20): WaterScore[] {
  return [...getScores()].sort((a, b) => b.overall_score - a.overall_score).slice(0, limit);
}

export function getAllStates(): string[] {
  return [...new Set(getScores().map(s => s.state))].sort();
}

export function getAllCities(state: string): string[] {
  return [...new Set(getScores().filter(s => s.state === state).map(s => s.city))].sort();
}

export function getGradeDistribution(state?: string): Record<string, number> {
  const scores = state ? getScoresByState(state) : getScores();
  const dist: Record<string, number> = { A: 0, B: 0, C: 0, D: 0, F: 0 };
  for (const s of scores) dist[s.grade] = (dist[s.grade] || 0) + 1;
  return dist;
}

export function getViolationsForSystem(systemId: string): Violation[] {
  return loadJSON<Violation>('violations.json').filter(v => v.system_id === systemId);
}

export function getContaminantsForSystem(systemId: string): ContaminantSample[] {
  return loadJSON<ContaminantSample>('contaminants.json').filter(c => c.system_id === systemId);
}

export function getTotalStats() {
  const scores = getScores();
  return {
    totalSystems: scores.length,
    totalPopulation: scores.reduce((sum, s) => sum + s.population_served, 0),
    avgScore: Math.round(scores.reduce((sum, s) => sum + s.overall_score, 0) / scores.length),
    gradeDistribution: getGradeDistribution(),
    states: getAllStates().length,
  };
}
